name = "abcdefg and hijklmop and qrstuv wxyz"
print(name[2:5])
print(name[2:5:1])
print(name[2:7:2])
print(name[:7:2])
print(name[2:])
print(name[2::2])
print(name[::-1])
print(name[-4:-1])
print(name[-4:-1:1])
print(name[-1:-4:-1])
print(name.find('qrs'))
print(name.find('qrsk', 15, 30))
print(name.index('qrs', 15, 30))
# print(name.index('qrks')) # substring error
print(name.count(" "))
print(name.rfind("and"))
print(name.rindex("efg"))
print(name.replace('efg', 'gfe'))
print(name.replace('and', 'AND', 1))
print(name.split(' '))
print(name.split(' ', 2))

mylist = ['aa', 'bb', 'cc']
print('..'.join(mylist))

mystr = "  hello word and itcast and itheima and Python  "
print(mystr.capitalize())
print(mystr.title())
print(mystr.upper())
print(mystr.lower())
print(mystr.lstrip())
print(mystr.rstrip())
print(mystr.strip())
print(mystr.startswith('cc'))
print(mystr.startswith('  '))
print(mystr.startswith('and', 15, 30))
print(mystr.endswith(' '))
print(mystr.endswith('Python  '))
print(mystr.endswith('Python  ', 15, 30))
print()
mystr2 = 'hello'
print(mystr2.ljust(10))
print(mystr2.ljust(10, '.'))
print(mystr2.rjust(10))
print(mystr2.rjust(10, '.'))
print(mystr2.center(10))
print(mystr2.center(10, '.'))
print()
print(mystr.isalpha())
print(mystr2.isalpha())
num1 = '12345'
print(num1.isalpha())
print(num1.isalnum())
print(num1.isdigit())
print(num1.isspace())